// <auto-generated />
using Chocolates.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chocolates.Migrations
{
    [DbContext(typeof(DbChocolatesContext))]
    [Migration("20240707044505_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chocolates.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdCategoria")
                        .HasName("PK__Categori__A2B5777C4A3A3A3D");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Descripcion = "Chocolates con sabor amargo",
                            Nombre = "Amargo"
                        },
                        new
                        {
                            IdCategoria = 2,
                            Descripcion = "Chocolate sabor semiamargo",
                            Nombre = "Semiamargo"
                        },
                        new
                        {
                            IdCategoria = 3,
                            Descripcion = "Chocolate oscuro",
                            Nombre = "Oscuro"
                        },
                        new
                        {
                            IdCategoria = 4,
                            Descripcion = "Chocolate blanco",
                            Nombre = "Blanco"
                        },
                        new
                        {
                            IdCategoria = 5,
                            Descripcion = "Chocolate relleno",
                            Nombre = "Relleno"
                        });
                });

            modelBuilder.Entity("Chocolates.Models.Chocolate", b =>
                {
                    b.Property<int>("IdChocolate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idChocolate");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChocolate"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("IdChocolate")
                        .HasName("PK__Chocolat__D3B9D1A3A3A3A3D");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Chocolate", (string)null);

                    b.HasData(
                        new
                        {
                            IdChocolate = 1,
                            Descripcion = "Chocolate oscuro con 70% de cacao",
                            IdCategoria = 1,
                            Imagen = "chocolate1.jpg",
                            Nombre = "Chocolate Amargo 70%",
                            Precio = 50.00m
                        },
                        new
                        {
                            IdChocolate = 2,
                            Descripcion = "Chocolate oscuro con 85% de cacao",
                            IdCategoria = 1,
                            Imagen = "chocolate2.jpg",
                            Nombre = "Chocolate Amargo 85%",
                            Precio = 60.00m
                        },
                        new
                        {
                            IdChocolate = 3,
                            Descripcion = "Chocolate semiamargo con 50% de cacao",
                            IdCategoria = 2,
                            Imagen = "chocolate3.jpg",
                            Nombre = "Chocolate Semiamargo 50%",
                            Precio = 40.00m
                        },
                        new
                        {
                            IdChocolate = 4,
                            Descripcion = "Chocolate semiamargo con 60% de cacao",
                            IdCategoria = 2,
                            Imagen = "chocolate4.jpg",
                            Nombre = "Chocolate Semiamargo 60%",
                            Precio = 45.00m
                        },
                        new
                        {
                            IdChocolate = 5,
                            Descripcion = "Chocolate oscuro con 75% de cacao",
                            IdCategoria = 3,
                            Imagen = "chocolate5.jpg",
                            Nombre = "Chocolate Oscuro 75%",
                            Precio = 55.00m
                        },
                        new
                        {
                            IdChocolate = 6,
                            Descripcion = "Chocolate oscuro con 90% de cacao",
                            IdCategoria = 3,
                            Imagen = "chocolate6.jpg",
                            Nombre = "Chocolate Oscuro 90%",
                            Precio = 65.00m
                        },
                        new
                        {
                            IdChocolate = 7,
                            Descripcion = "Chocolate blanco cremoso",
                            IdCategoria = 4,
                            Imagen = "chocolate7.jpg",
                            Nombre = "Chocolate Blanco",
                            Precio = 50.00m
                        },
                        new
                        {
                            IdChocolate = 8,
                            Descripcion = "Chocolate blanco con trozos de almendras",
                            IdCategoria = 4,
                            Imagen = "chocolate8.jpg",
                            Nombre = "Chocolate Blanco con Almendras",
                            Precio = 55.00m
                        },
                        new
                        {
                            IdChocolate = 9,
                            Descripcion = "Chocolate relleno de crema de fresa",
                            IdCategoria = 5,
                            Imagen = "chocolate9.jpg",
                            Nombre = "Chocolate Relleno de Fresa",
                            Precio = 60.00m
                        },
                        new
                        {
                            IdChocolate = 10,
                            Descripcion = "Chocolate relleno de crema de naranja",
                            IdCategoria = 5,
                            Imagen = "chocolate10.jpg",
                            Nombre = "Chocolate Relleno de Naranja",
                            Precio = 60.00m
                        });
                });

            modelBuilder.Entity("Chocolates.Models.Chocolate", b =>
                {
                    b.HasOne("Chocolates.Models.Categoria", "Categoria")
                        .WithMany("Chocolates")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK__Chocolate__idCat__3A81B327");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Chocolates.Models.Categoria", b =>
                {
                    b.Navigation("Chocolates");
                });
#pragma warning restore 612, 618
        }
    }
}
